### PR TITLE
Another round of English text improvements

### PR DESCRIPTION
**Pull request by mikkelking**
Zhang, here are some more changes to the English API documentation. still some way to go:)

Cheers

Mike

### CODE REVIEW

**Comment by zTree** [comment]
Please reFork zTree,  I fixed some error in your commit.

**Comment by mikkelking** [comment]
No problems, I think I forked my own branch by mistake. Was the error 
something I did wrong?

Is it better for me to re-fork every time I make changes, or should I 
stick with my own branch and just send pull requests?

Thanks

Mike

**Comment by zTree** [comment]
I have add you to the Collaborators.  Now you can pull & push in zTree. And I create new branch 'english',  You can pull & push use this branch,  I will merge 'english' branch to the 'master'.

your error is like....   

````
callback: {
		beforeCollapsefunction myBeforeCollapse
 	}
````

**Comment by mikkelking** [comment]
Thanks Zhang, I have re-cloned and have set my default branch to 
english, hopefully this will work ok.

I notice that there are some pages on your web site that are not in the 
repository, such as main.php, faq.php, demo.php etc

If you put them in the git repository I can fix those for you too - as 
they are the landing pages, they are probably more important to fix first.

Cheers

Mike

**Comment by zTree** [comment]
:)  The web site is in https://github.com/zTree/oldTreeBak ..... In this project is all of the zTree's source and web pages.  I think you can modify this project.   What do you think?

**Comment by mikkelking** [comment]
Zhang,

I forked the project, and having a look around, I can see some language 
files in

zTreeWeb/Web3.0_Design/lang/en

So I guess I just edit these?

In some pages the Chinese text appears as square boxes. I am using 
Netbeans, and have the character encoding set to UTF-8 - will that be a 
problem?

When I paste the text here:

技术支持

It looks ok, so I guess as long as I don't edit that text it will be OK?

Cheers

Mike

**Comment by zTree** [comment]
please wait.... You don't need to fork this project.  I will create 'english' branch for you.

I have checked the files in 'zTreeWeb/Web3.0_Design/lang/en'...there are not chinese text.  so  If you only paste the english, it will be ok.

**Comment by zTree** [comment]
I have create branch for you. Please pull it.

1. you can modify api files in '/zTreeWeb/web3.0_Design/api'
1. you can modify language files in 'zTreeWeb/Web3.0_Design/lang/en'

**Comment by mikkelking** [comment]
Ok, thanks, so I shouldn't work in zTree_v3 any more for the api?

**Comment by zTree** [comment]
Yes.  I will merge it to zTree_v3

**Pull request merged**
